version: '3.8'

services:
  aichatmpesa-backend:
    build: .
    container_name: aichatmpesa-backend
    expose:
      - "3343"  # AI Agent API
      - "3344"  # Webhook Server
    environment:
      # Core application settings
      - PYTHONPATH=/app
      - PORT=3343
      # Database
      - DATABASE_URL=sqlite:///./data/mpesa_sessions.db
      # M-Pesa Configuration (override with your values)
      - MPESA_ENVIRONMENT=${MPESA_ENVIRONMENT:-sandbox}
      - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
      - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
      - MPESA_BUSINESS_SHORT_CODE=${MPESA_BUSINESS_SHORT_CODE:-174379}
      - MPESA_PASSKEY=${MPESA_PASSKEY}
      - MPESA_CALLBACK_URL=${MPESA_CALLBACK_URL}
      # Twilio WhatsApp Configuration
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      # Google AI
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_GENAI_USE_VERTEXAI=${GOOGLE_GENAI_USE_VERTEXAI:-0}
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3343/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  app_data:
