version: '3.8'

services:
  mpesa-backend:
    build: .
    container_name: aichatmpesa-backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      # Override callback server URL for Docker internal communication
      - CALLBACK_SERVER_URL=http://localhost:8001
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: mpesa-ngrok
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    depends_on:
      - mpesa-backend
